spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://localhost:3306/drones
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    
fleet:
  capacity: 10
  
